DROP DATABASE IF EXISTS db;
CREATE DATABASE db;

USE db;


CREATE TABLE PARTIDAS (ID INT NOT NULL, NUM_JUG INT, DURACION FLOAT, PRIMARY KEY (ID)) ENGINE = InnoDB;


CREATE TABLE PERSONAJES (ID INT NOT NULL, FUERZA INT, HP INT, VEL INT, MAGIA INT, PRIMARY KEY (ID)) ENGINE = InnoDB;

CREATE TABLE USUARIOS (ID INT NOT NULL, NOMBRE VARCHAR(30), CORREO VARCHAR(30), PASSWORD VARCHAR(30), ID_PERS INT, SCORE INT, ID_PARTIDA INT, PRIMARY KEY (ID), FOREIGN KEY (ID_PERS) REFERENCES PERSONAJES(ID), FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDAS(ID)) ENGINE = InnoDB;

